### ISSUE TITLE
fromXML behavioural difference when converting to map or record

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-library#3714]
**Description:**
If the xml element contains a prefix, this is only applied to record conversions not maps.
<img width="601" alt="Screenshot 2022-11-26 at 16 45 35" src="https://user-images.githubusercontent.com/27669465/204085935-6a362ba1-7f73-4d27-900a-5c84a0f2893c.png">
<img width="1363" alt="Screenshot 2022-11-26 at 16 45 42" src="https://user-images.githubusercontent.com/27669465/204085939-fc4ce633-c012-471e-a289-dec8a5b89dec.png">

This also strips attributes, shouldnt this be similar to toJson conversion where attributes are marked as `@` prefix?

**Comment by kalaiyarasiganeshalingam** [comment]
Yes, this is expected behavior. When the expected type is not in the defined record type, we omit the namespace and attributes.

Yes, we can. But adding this prefix will cause more confusion and complexity while using the record.

If a user wants a namespace and attributes, they can use the `toJson` API.
