### ISSUE TITLE
Neglecting HTTP resources with tailing slashes

### ISSUE THREAD

**Issue by slahirucd7** [ballerina-platform/ballerina-library#5886]
**Description:**
Considere a scenario where there are two HTTP resources as `/abc` and `/abc/`
In ballerina those two resources are considering as the same.
But in other languages those are considered as two different resources.

**Steps to reproduce:**

```
import ballerina/http;


service on new http:Listener(9092) {

    resource function get rsc() returns string {
        return "without trailing slash";
    }

    resource function get rsc\/() returns string {
        return "with trailing slash";
    }
    resource function get rsc/[string a]() returns string {
        return "with trailing slash and path param " + a;
    }
    // This is not allowed to have in ballerina
    // resource function get rsc/[string a]\/() returns string {
    //     return "with trailing slash and path param" + a;
    // }
}
```

![image](https://github.com/wso2-enterprise/internal-support-ballerina/assets/40932779/1b69e3be-6e5f-480f-b714-4370b6657cd6)

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by TharmiganK** [comment]
@slahirucd7 Please note that the escaped slash in the resource method is considered as a part of `resource-path-segment` according to the spec. Therefore, to invoke such a resource, you should make a request with the path which has a slash as part of the path segment. Since slash is a reserved character, we should encode it,
```console
$ curl "http://localhost:9092/rsc%2F"

with trailing slash
```

So this is not equivalent to the resource which has an empty path segment(`/rsc/`). According to the Ballerina spec, resource functions should have a `resource-path-segment` or `resource-path-rest-param` after the slash. So currently it is not possible to support this. Please create a spec issue.

**Comment by slahirucd7** [comment]
Created the issue:
https://github.com/ballerina-platform/ballerina-lang/issues/41927
@TharmiganK  Could you please add relevant labels and inform the team regarding above ?
Thanks in advance
