### ISSUE TITLE
HTTP service redirects distinctly identified resource paths to a unified endpoint

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-library#5891]
**Description:**
The compiler distinguishes between resource paths `path` and `path\/` as distinct resource symbols. However, when HTTP requests are made to both `path` and `path/`, the server redirects both requests to the `path` resource. Despite the initial differentiation in the compiler, the server handles these paths interchangeably by directing requests to the canonical path endpoint.

**Steps to reproduce:**
1. Copy this code to a bal file and start the http service.
```ballerina
import ballerina/http;
service / on new http:Listener(8080) {
    resource function get path\/() returns string {
        return "Path1";
    }

    resource function get path() returns string {
        return "Path";
    }

}
```
2. `curl http://localhost:8080/path`
3. `curl http://localhost:8080/path/`

**Affected Versions:**
2201.8.4

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
[https://github.com/ballerina-platform/ballerina-lang/issues/41879](https://github.com/ballerina-platform/ballerina-lang/issues/41879)

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by TharmiganK** [comment]
@LakshanWeerasinghe In the first resource function the escaped slash is inferred as a part of the `resource-path-segment` according to the spec. So to hit the first resource you should make a request with a path which consists a slash. Since slashes are reserved, we should encode it in the path. So making the following cURL request will hit the first resource,
```console
$ curl "http://localhost:8080/path%2F"

Path1
```

Hence this is not equivalent to a path with an empty resource path segment(`/path/`). According to the Ballerina spec, resource functions should have a `resource-path-segment` or `resource-path-rest-param` after the slash. So currently it is not possible to support this. Please follow up on the lang issue to provide a solution from Ballerina spec.
