### ISSUE TITLE
The table name are empty in the generated SQL script when entities has doc comments 

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-library#6497]
**Description:**
$subject.

If there are doc comments for the entities defined in the model file like below,

```ballerina
# Represents a conference
#
# + id - The id of the conference
# + name - The name of the conference
public type Conference record {|
    readonly string id;
    string name;
|};
```

Generated SQL scripts are like below,

```sql
DROP TABLE IF EXISTS ``;

CREATE TABLE `` (
	`id` VARCHAR(191) NOT NULL,
	`name` VARCHAR(191) NOT NULL,
	PRIMARY KEY(`id`)
);
```

The table name is empty

**Comment by hasathcharu** [comment]
This issue identified is due to the doc comment being a valid `MetadataNode`, and the program falsely assuming this metadata node must be the `@sql:Name` annotation, and failing to extract the `value` from the annotation. This will be fixed in a later patch release. 

In the meantime there's a workaround as follows. It involves using the `@sql:Name` annotation to annotate the entity with a custom name for it's resulting table.

```Ballerina
# Represents a conference
#
# + id - The id of the conference
# + name - The name of the conference
@sql:Name {value:"Conference"}
public type Conference record {|
    readonly string id;
    string name;
|};
```

Please note that this may give you a compiler warning stating the mapped name and entity name is the same, hence making `@sql:Name` annotation redundant. However, the client will generate without any issues.
