### ISSUE TITLE
Generate a single file for a specific mode in the OpenAPI tool

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-library#6662]
**Description:**
- When the mode is set to client, it currently generates three files. Instead of generating three files, we should generate a single file that includes all the contents.
- Similarly, this should be done for the service mode as well.

**Comment by dilanSachi** [comment]
Had an offline discussion with @HindujaB .

In this approach there can be 2 issues that may arise.
1. If the file content is too much, there can be `File too large` errors at the codegen phase. But the current limit for this to happen is very high.
2. And also there maybe some performance impact depending on the code. However, there is no specific impact.

Therefore, we can add a flag to enable this so that even if there are issues, users can generate the files in the default format without any issues.
