### ISSUE TITLE
Dependency conflict warning with gRPC

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-library#7028]
**Description:**
Running the module lifecycle example on U10 - https://ballerina.io/learn/by-example/module-lifecycle/

```cmd
bal run test.bal 
Compiling source
        test.bal
ballerina/protobuf:1.6.1 [central.ballerina.io ->/<BAL_HOME>/repositories/central.ballerina.io/bala/ballerina/protobuf/1.6.1]  100% [==========] 18
        ballerina/protobuf:1.6.1 pulled from central successfully
        warning: Detected conflicting jar files:
                'protobuf-java-3.20.3.jar' dependency of 'ballerina/grpc' conflict with 'protobuf-java-3.25.5.jar' dependency of 'ballerina/protobuf'

Running executable

Hello world
```

The distribution build is also failing (output verification) due to this.

**Comment by HindujaB** [comment]
related to https://github.com/ballerina-platform/ballerina-library/issues/7013.
Happening because the grpc fix is not released yet.

**Comment by TharmiganK** [comment]
This is happening since [we have not updated the artifact id and group id in the protobuf module](https://github.com/ballerina-platform/module-ballerina-protobuf/blob/21baa2055a66c8b96e55fb9c7d097b4c0efeb881/ballerina/Ballerina.toml#L23). Thats why we cannot resolve the conflicts.

We need to add those. Btw releasing the patch for grpc with the same version can also fix the problem

@daneshk Can we add those in the `Ballerina.toml`?

**Comment by Nuvindu** [comment]
Updated the `protobuf-java` dependency in the `protobuf` module, just to be on the safe side.
https://github.com/ballerina-platform/module-ballerina-protobuf/pull/241

**Comment by Nuvindu** [comment]
This is fixed now
